name: Build and Deploy

on:
  push:
    branches:     
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact to github
        uses: actions/upload-artifact@v4
        with:
          name: pokemon-client-build
          path: dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get artifacts from github
        uses: actions/download-artifact@v4
        with:
          name: pokemon-client-build
      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          source_dir: 'dist'
          destination_dir: ''
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws_bucket: ${{ secrets.SITE_BUCKET_NAME }}