name: Build and Deploy

on:
  push:
    branches:     
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact to github
        uses: actions/upload-artifact@v4
        with:
          name: pokemon-client-build
          path: dist